# Used to limit GBIF search to a certain class
taxonomy.class = "Insecta" 

# EXCEL sctructure and format
excel.first_data_line = 3  # First line in file = 1
excel.col_taxon_name = "MYGathering[0][MYUnit][0][MYIdentification][0][MYTaxon]"
excel.col_taxon_author = "MYGathering[0][MYUnit][0][MYIdentification][0][MYAuthor]"
excel.col_taxon_rank = "MYGathering[0][MYUnit][0][MYIdentification][0][MYTaxonRank]"
# Where to add a family column. Integer (1 = first column etc)
# COmment out for no output
excel.add_gbifname_column_at = 1
excel.add_family_column_at = 1
excel.gbifname_column_title = "GBIF taxon name"
excel.family_column_title = "GBIF family"

# flush_GBIF_cache: set to 1 to clear local copy of GBIF data file. Rebuilding it will be slow!
gbif.flush_GBIF_cache = false
gbif.cachefile = "P:/h978/insect/Kahanpää/SMALL_TOOLS/gbif_taxon_fetch/gbifcache.dat"


